[package]
name = "gdk-electrum"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
edition = "2018"

[features]
android_log = ["android_logger"]

[dependencies]
log = "0.4.8"
rand = "0.6.5"
hex = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "*"
sha2 = "0.8.0"
aes-gcm-siv = "0.5.0"
gdk-common = { path = "../gdk_common" }
libc = "0.2"
android_logger = { version = "0.8.6", optional = true }
electrum-client = "0.3.0-beta.1"
chrono = "0.4.11"
ureq = { version = "1.0.0", features = ["json"] }
block-modes = "0.3.3"
aes = "0.3.2"
tempdir = "0.3.7"
secp256k1 = { version = "0.19.0", features = [ "recovery", "rand"] }
lazy_static = "1.4.0"

# remember to update secp256k1 deps if increasing this one, unfortunately we can't use the rexported one from bitcoin because we need recovery feature
bitcoin = { version = "0.25", features = [ "use-serde" ] }
elements = { version = "0.13", features = ["serde-feature"] }

[patch.crates-io]
bitcoin = { git = "https://github.com/shesek/rust-bitcoin", branch = "0.25.2-uint-serde", features = [ "use-serde" ] }
electrum-client = { git = "https://github.com/shesek/rust-electrum-client", branch = "202011-custom-ssl-stream" }
