[package]
name = "gdk-rust"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>", "Nadav Ivgi <nadav@shesek.info>"]
license = "(MIT)"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[features]
android_log = ["android_logger"]

[dependencies]
bitcoin = { version = "0.25.2", features = [ "use-serde" ] }
rand = "0.7.3"
gdk-electrum = { path = "gdk_electrum", features = ["android_log"] }
gdk-common = { path = "gdk_common" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
hex = "0.4.0"
dirs = "1.0"
chrono = "0.4.11"
log = "0.4.8"
android_logger = { version = "0.8.6", optional = true }
url = "1.7.2"
ureq = { version = "1.0.0", features = ["json"] }

[dev-dependencies]
tempdir = "0.3.7"
bitcoincore-rpc = { git="https://github.com/romanz/rust-bitcoincore-rpc", rev="637e895a0b73ffc21c8f62fa2c65b6fd1247785a" }
electrum-client = "0.3.0-beta.1"
elements = { version = "0.13", features = ["serde-feature"] }

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1
incremental = false

[patch.crates-io]
bitcoin = { git = "https://github.com/shesek/rust-bitcoin", branch = "0.25.2-uint-serde", features = [ "use-serde" ] }
